### ISSUE TITLE
Python Packaging

### ISSUE THREAD

**Issue by nabobalis** [Alexey-Stupishin/Magnetic-Field_Library#1]
Hello @Alexey-Stupishin,

I just wanted to get the ball re-rolling on the WIP items I did last week.

Since we want to keep compatibility with IDL, I was thinking that I can keep the original structure of the repository but then move all the Python files around instead.

This would allow you to keep one repository for this code. 

How does that sound?

**Comment by Alexey-Stupishin** [comment]
Dear Nabil,

Yes, I also think in this direction. So, finally it can be several repositories:

1. For pure C++ stuff (with all cpp/h, makefile and projects, dll for Windows);
2. Python wrapper repository, looks mostly as you proposed, but all C++ (not only common in src/pynlff/source as in your suggestion) will refer to C++ repository as Git submodule;
3. IDL wrapper in the same way
4. MATLAB wrapper
5. .......

I'm novice in the Python, especially in the infrastructure of a project, so now I investigate how to organize infrastructure files, like setup.py, yaml/toml etc., it will take some time to involve myself in this process. I would be highly appreciate if you will response to my stupid questions during my adaptation to this Python world.

Sincerely, 
Alexey

BTW, I ported potential field extrapolation (or, more precise, linear force free approach) to the Python, now I testing it. We can think how to include it, as separate repository or in the same package as NLFFF. I remember that it was the issue in sunkit_magex. Maybe my implementation will be helpful.

SY, Alexey

**Comment by nabobalis** [comment]
> Dear Nabil,
> 
> Yes, I also think in this direction. So, finally it can be several repositories:

I was thinking we could just keep it all together. That might be easier for you to look after instead of several repositories.
> 
> I'm novice in the Python, especially in the infrastructure of a project, so now I investigate how to organize infrastructure files, like setup.py, yaml/toml etc., it will take some time to involve myself in this process. I would be highly appreciate if you will response to my stupid questions during my adaptation to this Python world.

Happy to help.
 
> Sincerely, Alexey
> 
> BTW, I ported potential field extrapolation (or, more precise, linear force free approach) to the Python, now I testing it. We can think how to include it, as separate repository or in the same package as NLFFF. I remember that it was the issue in sunkit_magex. Maybe my implementation will be helpful.
> 
> SY, Alexey

That is great, if you would like, you could add it to sunkit_magex? Happy to help with that as well.

**Comment by nabobalis** [comment]
Hi @Alexey-Stupishin, I am very sorry for forgetting about this completely.

I see that you got https://pypi.org/project/pyAMaFiL/ out with wheels. I want to offer you and @vit1-irk congratulations. Packaging with wheels is not a trivial task.

**Comment by Alexey-Stupishin** [comment]
Dear @nabobalis, thanks, your help with package prototype was very helpful.
